name: bankomat
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  intl_utils: ^2.8.7
  hooks_riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true